---
title: "Descriptive statistics"
date: "2019/09/09"
---

```{r knitr-init, echo=F}
library(knitr)
## Global options
options(digits = 4)
opts_chunk$set(echo=F, cache=T, prompt=F, tidy=T, comment=NA, message=F, warning=F, dev="png", dev.args=list(type="cairo"), dpi=300)
color1 <- "#F8766D"
color2 <- "#00BFC4"
```

```{r packages, results='hide'}
# Load packages
.packages <- c("tidyverse", "rstatix", "crosstalk", "reactable", "htmltools", "ggstatsplot", "kableExtra")
.installed <- .packages %in% installed.packages()
if (length(.packages[!.installed])>0) install.packages(.packages[!.installed])
lapply(.packages, require, character.only=T)
```
  
# Purified and non-purified aliquots

```{r data-loading, results='hide'}
source("data-loading.R")
```

```{r descriptive-statistics-groups}
stats <- data %>%
  group_by(Peak, Method, Type) %>%
  get_summary_stats(Area, type = "mean_sd") %>%
  select(-c("variable"))

stats <- SharedData$new(stats)

bscols(
  widths = c(2, 10),
  list(
    tags$h3("Filter"),
    filter_select("Method", "Method", stats, ~Method),
    filter_select("Type", "Type", stats, ~Type),
    filter_select("Peak", "Peak", stats, ~Peak)
  ),
  reactable(stats, minRows = 10)
)
``` 

```{r bloxplot-groups-faceted}
ggplot(data, aes(x = Method, y = Area, colour = Type)) + 
  facet_wrap(vars(Peak), scales = "free") +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  ggtitle("Percentage of area covered by peaks of PSA") +
  xlab("") +
  ylab("% Area") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_bw()
```

# Non-purified aliquots

```{r bloxplot-groups-non-purified}
data %>%
  filter(Type == "Non-purified") %>%
  ggplot(aes(x = Peak, y = Area, colour = Method)) + 
  geom_boxplot() +
  ggtitle("Percentage of area covered by peaks of PSA for non-purified aliquots") +
  xlab("") +
  ylab("% Area") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_bw()
```


```{r bloxplot-groups-faceted-non-purified}
data %>%
  filter(Type == "Non-purified") %>%
  ggplot(aes(x = Method, y = Area)) + 
  facet_wrap(vars(Peak), scales = "free") +
  geom_boxplot(colour = color1) +
  ggtitle("Percentage of area covered by peaks of PSA for non-purified aliquots") +
  xlab("") +
  ylab("% Area") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_bw()
```


# Purified aliquots

```{r bloxplot-groups-purified}
data %>%
  filter(Type == "Purified") %>%
  ggplot(aes(x = Peak, y = Area, colour = Method)) + 
  geom_boxplot() +
  ggtitle("Percentage of area covered by peaks of PSA for purified aliquots") +
  xlab("") +
  ylab("% Area") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_bw()
```


```{r bloxplot-groups-faceted-purified}
data %>%
  filter(Type == "Purified") %>%
  ggplot(aes(x = Method, y = Area)) + 
  facet_wrap(vars(Peak), scales = "free") +
  geom_boxplot(colour = color1) +
  ggtitle("Percentage of area covered by peaks of PSA for purified aliquots") +
  xlab("") +
  ylab("% Area") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_bw()
```
